name: validate
on: [push]


jobs:
  lint_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          python-version: 3.7

      - name: install linting packages
        run: pip install -r tests/requirements.txt

      - name: flake8
        run: flake8 .

  test_code:
    runs-on: ${{ matrix.os }}
    needs: download_test_data
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python_version: [3.7, 3.6]

    steps:
      - uses: actions/checkout@v1

      - name: Setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          python-version: ${{ matrix.python_version }}
          activate-environment: test
          environment-file: .github/test_conda_env.yml
          condarc-file: .github/test_condarc.yml

      - name: install obsplus
        shell: bash -l {0}
        run: |
          pip install -e .[dev]

      - name: print package info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: download test data
        shell: bash -l {0}
        run: |
          git clone https://github.com/d-chambers/opsdata_test
          mv opsdata_test ~/opsdata

      - name: run test suite
        shell: bash -l {0}
        run: |
          pytest -s --cov obsplus --cov-append --cov-report term-missing

      - name: test docstrings
        shell: bash -l {0}
        run: |
          pytest obsplus --doctest-modules

      - name: test notebook docs
        shell: bash -l {0}
        run: |
          pytest docs --nbval

  coverage:
    runs-on: ubuntu-latest
    needs: test_code

    - uses: actions/checkout@v1

    - name: coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
